export const SET_TODO_LIST = "SET_TODO_LIST";
export const TODO_FETCH_REQUESTED = "TODO_FETCH_REQUESTED";
export const TODO_SEND_REQUESTED = "TODO_SEND_REQUESTED";
export const TODO_DELETE_REQUESTED = "TODO_DELETE_REQUESTED";
export const TODO_EDIT_REQUESTED = "TODO_EDIT_REQUESTED";
export const TODO_SEARCH_REQUESTED = "TODO_SEARCH_REQUESTED";
